services:
  mysql:
    image: mysql
    ports:
     - "3306:3306"
    expose:
  	 - "3306"
    environment:
     - MYSQL_USER=root
     - MYSQL_PASSWORD=12345678
     - MYSQL_DATABASE=db_tweet
     - MYSQL_ROOT_PASSWORD=12345678